image: node:8

.scripting: &utils |
  function setup_npm_token() {
    echo "//npmjs.artifacts.zxteam.net/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  }
  function verify_package_version() {
    local PACKAGE_VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json)
    echo "Tag $CI_COMMIT_REF_NAME . Package $PACKAGE_VERSION"
    if [ $PACKAGE_VERSION != $CI_COMMIT_REF_NAME ]; then
      echo "Package version ${PACKAGE_VERSION} is not same as tag version ${CI_COMMIT_REF_NAME}" >&2
      exit 255
    fi
  }

stages:
  - publish

publish to npmjs.artifacts.zxteam.net:
  stage: publish
  dependencies:
    - build
  before_script:
    - *utils
    - verify_package_version
    - setup_npm_token
  script:
    - npm publish --access=public
  only:
    - tags
